@startuml

class 登录页
class 帖子页
class 个人主页

class 账号控制 {
    +注册()
    +登录()
}
class 帖子控制 {
    +发布帖子()
    +删除帖子()
}
class 任务控制 {
    +上传证据()
    +任务判定()
}
class 积分控制 {
    +加积分()
    +扣积分()
    +计算排名()
}

class 用户 {
    -学号
    -密码
    -积分
    -完成率
}
class 帖子 {
    -标题
    -内容
    -发布者
}
class 任务 {
    -任务状态
    -证据
}
class 积分 {
    -积分值
    -记录时间
}
class 评价 {
    -评分
    -评语
}
class 证据 {
    -图片/文字
    -上传时间
}

账号控制 --> 用户
帖子控制 --> 帖子
任务控制 --> 任务
积分控制 --> 积分

任务 --> 证据
任务 --> 评价
用户 --> 积分
@enduml